### ISSUE TITLE
Desmume can't access save files

### ISSUE THREAD

**Issue by Delstrom2** [basharast/RetroArch-ARM#1]
Whenever I try to use the Desmume core, it attempts to load the game and then, right at the point where it would say it's creating or accessing the save file, gives me an error message about the data not being able to be written. I've tried looking on Desmume forums, and the only thing they say is to use a newer version of the program, which isn't really possible when there aren't regular releases of libretro cores for Arm64 systems.

Games I've tried so far: Phantom Hourglass (Europe), Bowser's Inside Story (USA)

What it looks like:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/78463422/158524922-aafb1fa3-81b0-46f1-83e0-3b4d5bcbba83.png">

Note: This is in Phantom Hourglass after you try to click to the main menu from startup.

dct and dsv files are created for the games when no save file is present. I don't know if they are corrupt.

Core config file desmume.opt saved as desmume.txt file below. 
[DeSmuME.txt](https://github.com/basharast/RetroArch-ARM/files/8259352/DeSmuME.txt)

**Comment by Delstrom2** [comment]
Basically, the reason I'm bringing this up is that I don't know if this project uses an older version of the Desmume core or if this is a recurring issue or if this is just me.

**Comment by basharast** [comment]
Hi, thanks for reporting this issue, 
I'm not sure if this issue related to VFS (Virtual Files System) in RetroArch for UWP
I will do some tests and let you know with possible solutions very soon.
also I will check if there is any recent fixes for this core.

**Comment by basharast** [comment]
Almost a year but I didn't forgot that, 
look like enabling option `Load Game Into Memory` will break game save
I will disable that in the next update for `Desmume` core, 
not released yet, trying to make `JIT` working it will make emulation very fast, but no luck until now.

**Comment by basharast** [comment]
Fixed in temporary release for the core.
