### ISSUE TITLE
Button input issues

### ISSUE THREAD

**Issue by holaimscott** [basharast/RetroArch-ARM#2]
Howdy,

There is an issue that's going on while using Retroarch by some users:

> The big one is the B button flipping between quick menu and gameplay, but also being menu select
> I'm not sure what's going on, this is the first time I've ever had this. Steam is off, no pad mapping running

This is using the AYN Odin, which has built in controllers (driver is being detected as an XBOX 360 controller). And the users have tried to remap buttons in the settings to sort this out.

Is this an issue with other controllers too? This might be something worth checking out.

Thank you so much!

**Comment by rajelaran** [comment]
Hi, I just tested this on Odin Base with Win11 and the B button issue appears to be resolved!
These handheld devices have a couple of custom rear buttons but none of the typical Windows Mobile buttons apparently, just a home button that functions the same as the Windows key and a built in "Xinput" controller that has the face buttons arranged incorrectly lol.

**Comment by holaimscott** [comment]
This works great @basharast ! @rajelaran was the original tester. And yeah, having a version for ARM devices that are not Windows Phones would be neat (or, is there a way to add a setting to allow to turn on or off this feature in your port?)

**Comment by basharast** [comment]
Great, Thanks for the testing.
I'm happy the issue is fixed and it will not affect on Windows Mobile users, now the back button will be linked only if the devices type if Windows Phone.. otherwise it will be ignored.
I already published new release: 
[](https://github.com/basharast/RetroArch-ARM/releases/tag/1.10.5)

**Comment by holaimscott** [comment]
You are the best, thank you for everything! :)
