### ISSUE TITLE
UWP certificate expired on 2022-12-12

### ISSUE THREAD

**Issue by vkapartzianis** [basharast/RetroArch-ARM#6]
The UWP package ([WindowRT.UWP.RetroArch.1.9.10.+Lumia640.7z](https://github.com/basharast/RetroArch-ARM/releases/download/1.10.6a/WindowRT.UWP.RetroArch.1.9.10.+Lumia640.7z)) can no longer be installed as the included certificate expired on 2022-12-12. Can you please update it?

---
![image](https://user-images.githubusercontent.com/1918344/213567709-91226161-7b69-4358-9c99-7bf1c9e616b9.png)

**Comment by basharast** [comment]
Hi, just updated the certificate, thanks for informing me.
