### ISSUE TITLE
Crashes when analysing a directory in manual scan

### ISSUE THREAD

**Issue by fnxln** [basharast/RetroArch-ARM#7]
When selecting to analyze a directory for manual scan it freezes and after that it get a pink screen then it closes,
i could provide ways to debug the app if you teach me to
thanks 💜

**Comment by basharast** [comment]
There will be new update with latest changes on original repo (1.14.0) hopefully today
I already fixed a lot of things and will try to check this too,
thanks for reporting this problem.

**Comment by fnxln** [comment]
Ty, if could help in something let me know, I bought a windows arm laptop yesterday and until now it has been an amazing experience
If you need testing let me know 😉

**Comment by basharast** [comment]
I hope this release will solve the issue,
https://github.com/basharast/RetroArch-ARM/releases/latest
