### ISSUE TITLE
Extreme slowdown on Surface RT

### ISSUE THREAD

**Issue by penny503** [basharast/RetroArch-ARM#8]
RetroArch runs at 2fps. I am pretty sure it is a graphics issue. Probably just the surface's hardware.

**Comment by basharast** [comment]
In general the UWP (No DirectX) version of RertroArch uses `[ANGLE](https://github.com/google/angle)` as bridge to deal with DirectX.
slow performance is expected but not 2fps, what cores did you tested?

as other option for Libretro core try [RetriXGold](https://github.com/basharast/RetrixGold)
I hope it will give better perfromance as it has render `SkipFrame` option

**Comment by basharast** [comment]
if this issue persist then unfortunately cannot be fixed because of hardware limitation.
