### ISSUE TITLE
Request: PUAE core

### ISSUE THREAD

**Issue by rubin55** [basharast/RetroArch-ARM#9]
Hi, I noticed you don't build the PUAE Amiga core, would be great if you could (I seem to remember you did have it in an older release, but it's missing from the corrent release).

**Comment by basharast** [comment]
Hi, will try to compile this core within few days

**Comment by basharast** [comment]
Unfortunately this wouldn't be easy for now, first message I got is this
![PUAE](https://user-images.githubusercontent.com/3244951/226212372-4907b296-4d2f-4455-8d03-42e657a8af15.PNG)

Most headers imported not for Windows, I will look to fix this if possible but that will take time.
